### PR TITLE
Format code fix error update picture

### PR DESCRIPTION
**Pull request by PkllonG**
Format code fix error update picture
@Helias

### CODE REVIEW

**Comment by Helias** [comment]
why did you close? it seems useful

**Comment by qyh214** [comment]
seems add zhcn ,maybe we should add language change button

**Comment by Helias** [comment]
I agree, we need a multi-lang system here

**Comment by MegaserverRU** [comment]
> I agree, we need a multi-lang system here

The site no longer works with AC ? Tested does not show players on the map, maybe you can tell me how to fix it?

**Comment by Helias** [comment]
it definitely works, here is an example https://www.chromiecraft.com/en/playermap/
probably you are putting some wrong configuration in the php config file

**Comment by MegaserverRU** [comment]
> it definitely works, here is an example https://www.chromiecraft.com/en/playermap/ probably you are putting some wrong configuration in the php config file

Configured everything, but does not show the players
[playermap_config.zip](https://github.com/azerothcore/playermap/files/10136545/playermap_config.zip)

**Comment by MegaserverRU** [comment]
> it definitely works, here is an example https://www.chromiecraft.com/en/playermap/ probably you are putting some wrong configuration in the php config file

[playermap_config (2).zip](https://github.com/azerothcore/playermap/files/10136548/playermap_config.2.zip)
Here is the file but does not display the players in any way

**Comment by yuanf225** [comment]
Why is this PR suspended

**Comment by Helias** [comment]
I never tested it, it seems good if anyone tested it I can merge it.

```
[playermap_config (2).zip](https://github.com/azerothcore/playermap/files/10136548/playermap_config.2.zip)
Here is the file but does not display the players in any way
```
I am not finding the time to check, I will do a test locally of this PR and of your config when I can :S

**Comment by MegaserverRU** [comment]
> I never tested it, it seems good if anyone tested it I can merge it.
> 
> ```
> [playermap_config (2).zip](https://github.com/azerothcore/playermap/files/10136548/playermap_config.2.zip)
> Here is the file but does not display the players in any way
> ```
> 
> I am not finding the time to check, I will do a test locally of this PR and of your config when I can :S

Well, thank you very much, I will be waiting for an answer

**Comment by Helias** [comment]
@MegaserverRU the playermap works perfectly to me if you do not use the GM
If you use the gm you have to run

`.gm visible on`
`.gm off`
moreover, to refresh the map data logout and login

afterward, you should see yourself on the map.

This PR works too so I am merging it, but ideally, would be great to have a conf to choose english / chinese or better, a button in the map to change language

**Comment by MegaserverRU** [comment]
> @MegaserverRU the playermap works perfectly to me if you do not use the GM If you use the gm you have to run
> 
> `.gm visible on` `.gm off` moreover, to refresh the map data logout and login
> 
> afterward, you should see yourself on the map.
> 
> This PR works too so I am merging it, but ideally, would be great to have a conf to choose english / chinese or better, a button in the map to change language

It's strange, but I log in from an ordinary player's account and still nothing is visible on the map (((
Thanks for the answer, though.

**Comment by Helias** [comment]
but at least the max-online player is correct? if not, there is probably an issue with the db connection

**Comment by MegaserverRU** [comment]
> but at least the max-online player is correct? if not, there is probably an issue with the db connection

Yes, everything was set up correctly, I deleted the site because I no longer know what to do to make it work for me. maybe you can throw off your customized version for the local host so that I can check if it will work for me

**Comment by Helias** [comment]
I did not edit anything, I used the master branch of this repository :(

I only changed the db credentials to make it work

**Comment by MegaserverRU** [comment]
> I did not edit anything, I used the master branch of this repository :(
> 
> I only changed the db credentials to make it work

strangely I set up the correct connection in the configuration and still without success

**Comment by Helias** [comment]
be sure that your PHP is able to connect to your database, make a quick check with the same db conf using https://www.php.net/manual/en/mysqli.quickstart.connections.php

**Comment by MegaserverRU** [comment]
> be sure that your PHP is able to connect to your database, make a quick check with the same db conf using https://www.php.net/manual/en/mysqli.quickstart.connections.php

Well, of course it connects, registration is already working on the server, maybe it's because I have MariaDB?

**Comment by Helias** [comment]
it could be possible, but mariadb differ slightly from Mysql so it should work, check if the db port is the same, be sure that PHP can connect correctly with it

p.s. contact me on discord, may it's faster

**Comment by MegaserverRU** [comment]
> it could be possible, but mariadb differ slightly from Mysql so it should work, check if the db port is the same, be sure that PHP can connect correctly with it
> 
> p.s. contact me on discord, may it's faster

My nickname in the discord is Shrack

**Pull request merged**
